In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nibabel as nib
import sys, os
sys.path.append(os.path.join(os.getcwd(), '../../'))

import numpy as np
from ext.lab2im import utils
from SynthSeg.brain_generator import BrainGenerator

In [8]:
# compare lable files
Synthseg_prior_dir = '../../data/labels_classes_priors'
generation_classes = np.load(f'{Synthseg_prior_dir}/generation_classes_contrast_specific.npy')
generation_labels = np.load(f'{Synthseg_prior_dir}/generation_labels.npy')
classes_names = np.load(f'{Synthseg_prior_dir}/synthseg_segmentation_names.npy')
output_labels = np.load(f'{Synthseg_prior_dir}/synthseg_segmentation_labels.npy')
prior_means = np.load(f'{Synthseg_prior_dir}/prior_means_t1.npy')
prior_stds = np.load(f'{Synthseg_prior_dir}/prior_stds_t1.npy')
print("Length of generation_classes:", len(generation_classes))
print("Length of generation_labels:", len(generation_labels))
print("Length of classes_names:", len(classes_names))
print("Length of output_labels:", len(output_labels))
print("Shape of prior_means:", prior_means.shape)
print("Shape of prior_stds:", prior_stds.shape)
print(len(np.unique(generation_classes)))
# Create a DataFrame with the class names and corresponding prior means/stds
df = pd.DataFrame({
    'Generation Label': generation_labels,
    'Generation Class': generation_classes,
    'Structure': classes_names,
    'output_labels': output_labels,
})

print("prior_means", prior_means)
print()
print("prior_stds", prior_stds)

display(df)

Length of generation_classes: 54
Length of generation_labels: 54
Length of classes_names: 54
Length of output_labels: 54
Shape of prior_means: (2, 25)
Shape of prior_stds: (2, 25)
25
prior_means [[  7.          44.43852646 160.29378443  96.29526152 135.95211069
   88.15506261 129.52385575 124.05468047 151.79945792 142.53280645
  116.10473738  86.83433108  59.62853626 129.78496267 126.37696696
   18.11697145  93.90532281 117.13488728  69.91289748 113.7338777
   68.23628889  48.42668289  30.19849003  94.24268292 144.4557237 ]
 [  1.75        11.21000137  21.65584467  12.17831661  13.41123838
   10.55970441  17.68538813  15.72768241  19.51073198  16.05725779
   14.8217615   17.47509896  10.4086569   12.2351825   24.79729954
    3.8432211    9.12899967  11.66694586   9.24940558  12.41801427
   11.09552493   8.56551669   6.86072804  18.31996116  16.31849085]]

prior_stds [[ 5.         25.56555604 15.63223578 18.91828816 15.34013798 17.0927207
  19.58860262 13.80592264  8.55665307 21.1277327

Generation Label  Generation Class                         Structure  \
0                  0                 0                        background   
1                 14                 1                     3rd ventricle   
2                 15                 1                     4th ventricle   
3                 16                13                        brain-stem   
4                 24                 1                        background   
5                 72                 1                        background   
6                 85                 2                        background   
7                502                14                        background   
8                506                15                        background   
9                507                16                        background   
10               508                17                        background   
11               509                18                        background   
12               511                19                        background   
13               512                20                        background   
14               514                21                        background   
15               515                22                        background   
16               516                23                        background   
17               530                24                        background   
18                 2                 2        left cerebral white matter   
19                 3                 3              left cerebral cortex   
20                 4                 1            left lateral ventricle   
21                 5                 1   left inferior lateral ventricle   
22                 7                 4      left cerebellum white matter   
23                 8                 5            left cerebellum cortex   
24                10                 6                     left thalamus   
25                11                 3                      left caudate   
26                12                 7                      left putamen   
27                13                 8                     left pallidum   
28                17                 3                  left hippocampus   
29                18                 3                     left amygdala   
30                25                10        left cerebral white matter   
31                26                 3               left accumbens area   
32                28                 9                   left ventral DC   
33                30                11                        background   
34               136                12            left lateral ventricle   
35               137                12   left inferior lateral ventricle   
36                41                 2       right cerebral white matter   
37                42                 3             right cerebral cortex   
38                43                 1           right lateral ventricle   
39                44                 1  right inferior lateral ventricle   
40                46                 4     right cerebellum white matter   
41                47                 5           right cerebellum cortex   
42                49                 6                    right thalamus   
43                50                 3                     right caudate   
44                51                 7                     right putamen   
45                52                 8                    right pallidum   
46                53                 3                 right hippocampus   
47                54                 3                    right amygdala   
48                57                10       right cerebral white matter   
49                58                 3              right accumbens area   
50                60                 9                  right ventral DC   
51                62                11              

In [15]:
output_labels = np.load('priors/output_labels_reorganized.npy',allow_pickle=True)
generation_labels = np.load('priors/generation_labels_reorganized.npy',allow_pickle=True)
classes_names = np.load('priors/classes_names_reorganized.npy',allow_pickle=True)
generation_classes = np.load('priors/generation_classes_reorganized.npy',allow_pickle=True)
prior_means_t1 = np.load('priors/t1_mean_class_based.npy')
prior_stds_t1 = np.load('priors/t1_std_class_based.npy')

print("Length of generation_classes:", len(generation_classes))
print("Length of generation_labels:", len(generation_labels))
print("Length of classes_names:", len(classes_names))
print("Length of output_labels:", len(output_labels))
print("Shape of prior_means:", prior_means_t1.shape)
print("Shape of prior_stds:", prior_stds_t1.shape)

print (len(np.unique(generation_classes)))

print("prior_means", prior_means_t1)
print()
print("prior_stds", prior_stds_t1)

df = pd.DataFrame({
    'Generation Label': generation_labels,
    'Generation Class': generation_classes,
    'Structure': classes_names,
    'output_labels': output_labels
})

display(df)
# Save DataFrame to CSV
df.to_csv('priors/labels_mapping.csv', index=False)


Length of generation_classes: 33
Length of generation_labels: 33
Length of classes_names: 33
Length of output_labels: 33
Shape of prior_means: (2, 15)
Shape of prior_stds: (2, 15)
15
prior_means [[ 930. 5500. 1500. 5500. 1500. 1080. 1450. 1310. 1050. 5500. 1500. 1400.
  5500. 1500.  930.]
 [ 820. 3800. 1250. 3800. 1250. 1060. 1250. 1100.  840. 3800. 1300. 1200.
  3800. 1250.  820.]]

prior_stds [[ 40. 400. 100. 400. 100.  70.  90.  70.  70. 400.  70. 200. 400. 100.
   40.]
 [ 20. 200.  30. 200.  30.  40.  70.  30.  30. 200.  50.  50. 200.  30.
   20.]]


Generation Label  Generation Class                         Structure  \
0                  0                 0                        background   
1                 14                 1                     3rd ventricle   
2                 15                 1                     4th ventricle   
3                 16                10                        brain-stem   
4                 24                 1                               CSF   
5                  2                 2        left cerebral white matter   
6                  3                 3              left cerebral cortex   
7                  4                 1            left lateral ventricle   
8                  5                 1   left inferior lateral ventricle   
9                  7                 4      left cerebellum white matter   
10                 8                 5            left cerebellum cortex   
11                10                 6                     left thalamus   
12                11                 7                      left caudate   
13                12                 8                      left putamen   
14                13                 9                     left pallidum   
15                17                11                  left hippocampus   
16                18                12                     left amygdala   
17                26                13               left accumbens area   
18                28                14                   left ventral DC   
19                41                 2       right cerebral white matter   
20                42                 3             right cerebral cortex   
21                43                 1           right lateral ventricle   
22                44                 1  right inferior lateral ventricle   
23                46                 4     right cerebellum white matter   
24                47                 5           right cerebellum cortex   
25                49                 6                    right thalamus   
26                50                 7                     right caudate   
27                51                 8                     right putamen   
28                52                 9                    right pallidum   
29                53                11                 right hippocampus   
30                54                12                    right amygdala   
31                58                13              right accumbens area   
32                60                14                  right ventral DC   

    output_labels  
0               0  
1              14  
2              15  
3              16  
4              24  
5               2  
6               3  
7               4  
8               5  
9               7  
10              8  
11             10  
12             11  
13             12  
14             13  
15             17  
16             18  
17             26  
18             28  
19             41  
20             42  
21             43  
22             44  
23             46  
24             47  
25             49  
26             50  
27             51  
28             52  
29             53  
30             54  
31             58  
32             60

In [26]:
prior_means_t1 = np.load('priors/t1_mean_updated.npy')
prior_stds_t1 = np.load('priors/t1_std_updated.npy')
prior_means_t2 = np.load('priors/t2_mean_updated.npy')
prior_stds_t2 = np.load('priors/t2_std_updated.npy')
prior_means_pd = np.load('priors/pd_mean_updated.npy')
prior_stds_pd = np.load('priors/pd_std_updated.npy')
df = pd.DataFrame({
    'Generation Class': np.unique(generation_classes),
    't1_mean_upper': prior_means_t1[0,:],
    't1_mean_lower': prior_means_t1[1,:],
    't1_std_upper': prior_stds_t1[0,:],
    't1_std_lower': prior_stds_t1[1,:],
    't2_mean_upper': prior_means_t2[0,:],
    't2_mean_lower': prior_means_t2[1,:],
    't2_std_upper': prior_stds_t2[0,:],
    't2_std_lower': prior_stds_t2[1,:],
    'pd_mean_upper': prior_means_pd[0,:],
    'pd_mean_lower': prior_means_pd[1,:],
    'pd_std_upper': prior_stds_pd[0,:],
    'pd_std_lower': prior_stds_pd[1,:]
})
# df.to_csv('priors/labels_relaxometry_priors.csv', index=False)

df



Generation Class  t1_mean_upper  t1_mean_lower  t1_std_upper  \
0                  0              0              0             0   
1                  1           5500           3800           400   
2                  2            900            750            20   
3                  3           1500           1250           100   
4                  4            900            750            20   
5                  5           1500           1250           100   
6                  6           1080           1060            70   
7                  7           1450           1250            90   
8                  8           1310           1100            70   
9                  9           1050            840            70   
10                10            900            750            20   
11                11           1500           1300            70   
12                12           1400           1200           200   
13                13           1500           1250           100   
14                14           1500           1250           100   

    t1_std_lower  t2_mean_upper  t2_mean_lower  t2_std_upper  t2_std_lower  \
0              0              0              0             0             0   
1            200           2000           1000            50            30   
2             10             85             75             5             0   
3             30            135             95             7             2   
4             10             85             75             5             0   
5             30            135             95             7             2   
6             40             72             60             3             0   
7             70             75             60             7             2   
8             30             63             57             5             2   
9             30            135             95             7             2   
10            10             85             75             5             0   
11            50            130            110             9             3   
12            50            100             95            10             5   
13            30            135             95             7             2   
14            30            135             95             7             2   

    pd_mean_upper  pd_mean_lower  pd_std_upper  pd_std_lower  
0               0              0             0             0  
1              98             95             2             0  
2              68             65             5             3  
3              85             80             5             1  
4              68             65             5             3  
5              85             80             5             1  
6              76             75             5             1  
7              82             79             5             1  
8              82             79             5             1  
9              85             80             5             1  
10             68             65             5             3  
11             83             81             2             1  
12             85             80             5             1  
13             85             80             5             1  
14             85             80             5             1

In [25]:
df = pd.read_csv('labels_relaxometry_priors.csv')
# Extract arrays from dataframe with upper/lower limits as rows
t1_mean = np.array([df['t1_mean_upper'].values, df['t1_mean_lower'].values])
t1_std = np.array([df['t1_std_upper'].values, df['t1_std_lower'].values])
t2_mean = np.array([df['t2_mean_upper'].values, df['t2_mean_lower'].values]) 
t2_std = np.array([df['t2_std_upper'].values, df['t2_std_lower'].values])
pd_mean = np.array([df['pd_mean_upper'].values, df['pd_mean_lower'].values])
pd_std = np.array([df['pd_std_upper'].values, df['pd_std_lower'].values])

# Save arrays
np.save('priors/t1_mean_updated.npy', t1_mean)
np.save('priors/t1_std_updated.npy', t1_std)
np.save('priors/t2_mean_updated.npy', t2_mean)
np.save('priors/t2_std_updated.npy', t2_std)
np.save('priors/pd_mean_updated.npy', pd_mean)
np.save('priors/pd_std_updated.npy', pd_std)


In [39]:
# test generation using priors from synthseg repo
# This works, the issues lies within my label file preparation
path_label_map = r'/mnt/hdd0/download/oasis-1/brain_segmentations/OAS1_0001_synthseg.nii.gz'
result_dir = r'/home/dual4090/lab/github/SynthSeg/output_example/test_qmri_on_synthseg_prior/'
n_examples = 5
randomise_res = False
prior_distributions = 'normal'
data_res = np.array([1., 1., 1.])  
thickness = np.array([1., 1., 1.])
n_neutral_labels = 18
output_shape = 256



t1_brain_generator = BrainGenerator(labels_dir=path_label_map,
                                 generation_labels=generation_labels,
                                 output_labels=output_labels,
                                 n_neutral_labels=n_neutral_labels,
                                 output_shape=output_shape,
                                 prior_distributions=prior_distributions,
                                 generation_classes=generation_classes,
                                 prior_means=prior_means,
                                 prior_stds=prior_stds,
                                 randomise_res=randomise_res,
                                 data_res=data_res,
                                 thickness=thickness,
                                 #disable deformation
                                 scaling_bounds=0,        # Disable scaling
                                 rotation_bounds=0,       # Disable rotation
                                 shearing_bounds=0,       # Disable shearing
                                 translation_bounds=False, # Disable translation
                                 nonlin_std=0,           # Disable non-linear deformation
                                 nonlin_scale=0,  
                                 bias_field_std=0.00250
                                 )

for n in range(n_examples):

    # generate new image and corresponding labels
    im, lab = t1_brain_generator.generate_brain()

    # save output image and label map
    utils.save_volume(im, t1_brain_generator.aff, t1_brain_generator.header,
                      os.path.join(result_dir, 't1map_%s.nii.gz' % n))
    utils.save_volume(lab, t1_brain_generator.aff, t1_brain_generator.header,
                      os.path.join(result_dir, 'labels_%s.nii.gz' % n))

In [153]:
# t1_mean = np.load('priors/t1_mean.npy')
# t1_std = np.load('priors/t1_std.npy')
# t2_mean = np.load('priors/t2_mean.npy')
# t2_std = np.load('priors/t2_std.npy')
# pd_mean = np.load('priors/pd_mean.npy')
# pd_std = np.load('priors/pd_std.npy')

# num_classes = len(np.unique(generation_classes))
# t1_mean_class_based = np.zeros((num_classes, 2))
# t1_std_class_based = np.zeros((num_classes, 2))
# t2_mean_class_based = np.zeros((num_classes, 2))
# t2_std_class_based = np.zeros((num_classes, 2))
# pd_mean_class_based = np.zeros((num_classes, 2))
# pd_std_class_based = np.zeros((num_classes, 2))

# for i in range(num_classes):
#     #assume left and right are paired always and have same values
#     class_index=np.where(np.array(generation_classes) == i)

#     t1_mean_class_based[i,0] = t1_mean[0,class_index[0][0]]
#     t1_mean_class_based[i,1] = t1_mean[1,class_index[0][0]]
#     t1_std_class_based[i,0] = t1_std[0,class_index[0][0]]
#     t1_std_class_based[i,1] = t1_std[1,class_index[0][0]]
#     t2_mean_class_based[i,0] = t2_mean[0,class_index[0][0]]
#     t2_mean_class_based[i,1] = t2_mean[1,class_index[0][0]]
#     t2_std_class_based[i,0] = t2_std[0,class_index[0][0]]
#     t2_std_class_based[i,1] = t2_std[1,class_index[0][0]]
#     pd_mean_class_based[i,0] = pd_mean[0,class_index[0][0]]
#     pd_mean_class_based[i,1] = pd_mean[1,class_index[0][0]]
#     pd_std_class_based[i,0] = pd_std[0,class_index[0][0]]
#     pd_std_class_based[i,1] = pd_std[1,class_index[0][0]]

#     np.save('priors/t1_mean_class_based.npy', t1_mean_class_based.T)
#     np.save('priors/t1_std_class_based.npy', t1_std_class_based.T)
#     np.save('priors/t2_mean_class_based.npy', t2_mean_class_based.T)
#     np.save('priors/t2_std_class_based.npy', t2_std_class_based.T)
#     np.save('priors/pd_mean_class_based.npy', pd_mean_class_based.T)
#     np.save('priors/pd_std_class_based.npy', pd_std_class_based.T)




In [48]:
output_labels = np.load('priors/output_labels_reorganized.npy',allow_pickle=True)
generation_labels = np.load('priors/generation_labels_reorganized.npy',allow_pickle=True)
classes_names = np.load('priors/classes_names_reorganized.npy',allow_pickle=True)
generation_classes = np.load('priors/generation_classes_reorganized.npy',allow_pickle=True)

t1_mean = np.load('priors/t1_mean_updated.npy')
t1_std = np.load('priors/t1_std_updated.npy')
t2_mean = np.load('priors/t2_mean_updated.npy')
t2_std = np.load('priors/t2_std_updated.npy')
pd_mean = np.load('priors/pd_mean_updated.npy')
pd_std = np.load('priors/pd_std_updated.npy')

path_label_map = r'/mnt/hdd0/download/oasis-1/brain_segmentations/OAS1_0001_synthseg.nii.gz'
result_dir = r'/home/dual4090/lab/github/SynthSeg/output_example/test_qmri/'
n_examples = 5
randomise_res = False
prior_distributions = 'normal'
data_res = np.array([0.25, 0.25, 0.25])  
thickness = np.array([0.25, 0.25, 0.25])
n_neutral_labels = 18
output_shape = 1024


In [49]:
print(t1_mean)
print(t1_std)


print(t2_mean)
print(t2_std)

print(pd_mean)
print(pd_std)

print(len(np.unique(generation_classes)))
print(t1_mean.shape)
# the number is the same? does this mean that the distribution for background should be specified?
# values are wrong! The value for CSF had been mapped onto white matter
# redo values in proper manner & document on overleaf


[[   0 5500  900 1500  900 1500 1080 1450 1310 1050  900 1500 1400 1500
  1500]
 [   0 3800  750 1250  750 1250 1060 1250 1100  840  750 1300 1200 1250
  1250]]
[[  0 400  20 100  20 100  70  90  70  70  20  70 200 100 100]
 [  0 200  10  30  10  30  40  70  30  30  10  50  50  30  30]]
[[   0 2000   85  135   85  135   72   75   63  135   85  130  100  135
   135]
 [   0 1000   75   95   75   95   60   60   57   95   75  110   95   95
    95]]
[[ 0 50  5  7  5  7  3  7  5  7  5  9 10  7  7]
 [ 0 30  0  2  0  2  0  2  2  2  0  3  5  2  2]]
[[ 0 98 68 85 68 85 76 82 82 85 68 83 85 85 85]
 [ 0 95 65 80 65 80 75 79 79 80 65 81 80 80 80]]
[[0 2 5 5 5 5 5 5 5 5 5 2 5 5 5]
 [0 0 3 1 3 1 1 1 1 1 3 1 1 1 1]]
15
(2, 15)


In [51]:


t1_brain_generator = BrainGenerator(labels_dir=path_label_map,
                                 generation_labels=generation_labels,
                                 output_labels=output_labels,
                                 n_neutral_labels=n_neutral_labels,
                                 output_shape=output_shape,
                                 prior_distributions=prior_distributions,
                                 generation_classes=generation_classes,
                                 prior_means=t1_mean,
                                 prior_stds=t1_std,
                                 randomise_res=randomise_res,
                                 data_res=data_res,
                                 thickness=thickness,
                                 flipping=False,
                                 #disable deformation
                                 scaling_bounds=0,        # Disable scaling
                                 rotation_bounds=0,       # Disable rotation
                                 shearing_bounds=0,       # Disable shearing
                                 translation_bounds=False, # Disable translation
                                 nonlin_std=0,           # Disable non-linear deformation
                                 nonlin_scale=0,  
                                 bias_field_std=0.00250
                                 )

for n in range(n_examples):

    # generate new image and corresponding labels
    im, lab = t1_brain_generator.generate_brain()
    # Threshold negative values to small epsilon
    epsilon = 1e-6
    im[im < 0] = epsilon
    # save output image and label map
    utils.save_volume(im, t1_brain_generator.aff, t1_brain_generator.header,
                      os.path.join(result_dir, 't1map_%s.nii.gz' % n))
    utils.save_volume(lab, t1_brain_generator.aff, t1_brain_generator.header,
                      os.path.join(result_dir, 'labels_%s.nii.gz' % n))


In [52]:


t2_brain_generator = BrainGenerator(labels_dir=path_label_map,
                                 generation_labels=generation_labels,
                                 output_labels=output_labels,
                                 n_neutral_labels=n_neutral_labels,
                                 output_shape=output_shape,
                                 prior_distributions=prior_distributions,
                                 generation_classes=generation_classes,
                                 prior_means=t2_mean,
                                 prior_stds=t2_std,
                                 randomise_res=randomise_res,
                                 data_res=data_res,
                                 thickness=thickness,
                                 flipping=False,
                                 #disable deformation
                                 scaling_bounds=0,        # Disable scaling
                                 rotation_bounds=0,       # Disable rotation
                                 shearing_bounds=0,       # Disable shearing
                                 translation_bounds=False, # Disable translation
                                 nonlin_std=0,           # Disable non-linear deformation
                                 nonlin_scale=0,  
                                 bias_field_std=0.00250
                                 )

for n in range(n_examples):

    # generate new image and corresponding labels
    im, lab = t2_brain_generator.generate_brain()
    # Threshold negative values to small epsilon
    epsilon = 1e-6
    im[im < 0] = epsilon
    # save output image and label map
    utils.save_volume(im, t2_brain_generator.aff, t2_brain_generator.header,
                      os.path.join(result_dir, 't2map_%s.nii.gz' % n))
    utils.save_volume(lab, t2_brain_generator.aff, t2_brain_generator.header,
                      os.path.join(result_dir, 'labels_%s.nii.gz' % n))

In [54]:


pd_brain_generator = BrainGenerator(labels_dir=path_label_map,
                                 generation_labels=generation_labels,
                                 output_labels=output_labels,
                                 n_neutral_labels=n_neutral_labels,
                                 output_shape=output_shape,
                                 prior_distributions=prior_distributions,
                                 generation_classes=generation_classes,
                                 prior_means=pd_mean,
                                 prior_stds=pd_std,
                                 randomise_res=randomise_res,
                                 data_res=data_res,
                                 thickness=thickness,
                                 flipping=False,
                                 #disable deformation
                                 scaling_bounds=0,        # Disable scaling
                                 rotation_bounds=0,       # Disable rotation
                                 shearing_bounds=0,       # Disable shearing
                                 translation_bounds=False, # Disable translation
                                 nonlin_std=0,           # Disable non-linear deformation
                                 nonlin_scale=0,  
                                 bias_field_std=0.0
                                 )

for n in range(n_examples):

    # generate new image and corresponding labels
    im, lab = pd_brain_generator.generate_brain()
    # Rescale image values to range [0, 100]
    im_min = im.min()
    im_max = im.max()
    im = 100 * (im - im_min) / (im_max - im_min)
    # save output image and label map
    utils.save_volume(im, pd_brain_generator.aff, pd_brain_generator.header,
                      os.path.join(result_dir, 'pdmap_%s.nii.gz' % n))
    utils.save_volume(lab, pd_brain_generator.aff, pd_brain_generator.header,
                      os.path.join(result_dir, 'labels_%s.nii.gz' % n))

In [ ]:
# There seems to be an error in the way that the values are drawn? 
# Look at PD values unscaled, sometimes the values can go way above 100?
# Image orientation is wrong?